export const BOARD_SIZE = 15;
export const CENTER_INDEX = 7;
export const RACK_SIZE = 7;
export const BINGO_BONUS = 50;
export const EXCHANGE_MIN_BAG_TILES = 7;
export const STORAGE_KEY = "scrabble-mobile-local";

export const LETTER_DISTRIBUTION = [
  { letter: "A", count: 9, points: 1 },
  { letter: "B", count: 2, points: 3 },
  { letter: "C", count: 2, points: 3 },
  { letter: "D", count: 3, points: 2 },
  { letter: "E", count: 15, points: 1 },
  { letter: "F", count: 2, points: 4 },
  { letter: "G", count: 2, points: 2 },
  { letter: "H", count: 2, points: 4 },
  { letter: "I", count: 8, points: 1 },
  { letter: "J", count: 1, points: 8 },
  { letter: "K", count: 1, points: 10 },
  { letter: "L", count: 5, points: 1 },
  { letter: "M", count: 3, points: 2 },
  { letter: "N", count: 6, points: 1 },
  { letter: "O", count: 6, points: 1 },
  { letter: "P", count: 2, points: 3 },
  { letter: "Q", count: 1, points: 8 },
  { letter: "R", count: 6, points: 1 },
  { letter: "S", count: 6, points: 1 },
  { letter: "T", count: 6, points: 1 },
  { letter: "U", count: 6, points: 1 },
  { letter: "V", count: 2, points: 4 },
  { letter: "W", count: 1, points: 10 },
  { letter: "X", count: 1, points: 10 },
  { letter: "Y", count: 1, points: 10 },
  { letter: "Z", count: 1, points: 10 },
  { letter: "?", count: 2, points: 0 }
];

export const PREMIUM_CELLS = {
  "0,0": { type: "TW", label: "MT" },
  "0,7": { type: "TW", label: "MT" },
  "0,14": { type: "TW", label: "MT" },
  "7,0": { type: "TW", label: "MT" },
  "7,14": { type: "TW", label: "MT" },
  "14,0": { type: "TW", label: "MT" },
  "14,7": { type: "TW", label: "MT" },
  "14,14": { type: "TW", label: "MT" },
  "1,1": { type: "DW", label: "MD" },
  "2,2": { type: "DW", label: "MD" },
  "3,3": { type: "DW", label: "MD" },
  "4,4": { type: "DW", label: "MD" },
  "7,7": { type: "STAR", label: "★" },
  "10,10": { type: "DW", label: "MD" },
  "11,11": { type: "DW", label: "MD" },
  "12,12": { type: "DW", label: "MD" },
  "13,13": { type: "DW", label: "MD" },
  "1,13": { type: "DW", label: "MD" },
  "2,12": { type: "DW", label: "MD" },
  "3,11": { type: "DW", label: "MD" },
  "4,10": { type: "DW", label: "MD" },
  "10,4": { type: "DW", label: "MD" },
  "11,3": { type: "DW", label: "MD" },
  "12,2": { type: "DW", label: "MD" },
  "13,1": { type: "DW", label: "MD" },
  "1,5": { type: "TL", label: "LT" },
  "1,9": { type: "TL", label: "LT" },
  "5,1": { type: "TL", label: "LT" },
  "5,5": { type: "TL", label: "LT" },
  "5,9": { type: "TL", label: "LT" },
  "5,13": { type: "TL", label: "LT" },
  "9,1": { type: "TL", label: "LT" },
  "9,5": { type: "TL", label: "LT" },
  "9,9": { type: "TL", label: "LT" },
  "9,13": { type: "TL", label: "LT" },
  "13,5": { type: "TL", label: "LT" },
  "13,9": { type: "TL", label: "LT" },
  "0,3": { type: "DL", label: "LD" },
  "0,11": { type: "DL", label: "LD" },
  "2,6": { type: "DL", label: "LD" },
  "2,8": { type: "DL", label: "LD" },
  "3,0": { type: "DL", label: "LD" },
  "3,7": { type: "DL", label: "LD" },
  "3,14": { type: "DL", label: "LD" },
  "6,2": { type: "DL", label: "LD" },
  "6,6": { type: "DL", label: "LD" },
  "6,8": { type: "DL", label: "LD" },
  "6,12": { type: "DL", label: "LD" },
  "7,3": { type: "DL", label: "LD" },
  "7,11": { type: "DL", label: "LD" },
  "8,2": { type: "DL", label: "LD" },
  "8,6": { type: "DL", label: "LD" },
  "8,8": { type: "DL", label: "LD" },
  "8,12": { type: "DL", label: "LD" },
  "11,0": { type: "DL", label: "LD" },
  "11,7": { type: "DL", label: "LD" },
  "11,14": { type: "DL", label: "LD" },
  "12,6": { type: "DL", label: "LD" },
  "12,8": { type: "DL", label: "LD" },
  "14,3": { type: "DL", label: "LD" },
  "14,11": { type: "DL", label: "LD" }
};

export const PREMIUM_STYLES = {
  TW: "bg-ember text-white",
  DW: "bg-gold text-ink",
  TL: "bg-ocean text-ink",
  DL: "bg-rose text-ink",
  STAR: "bg-moss text-white",
  NORMAL: "bg-[#f1dfb7] text-ink/40"
};
